CREATE PROCEDURE PUBLISHED.FACT_ALL_GAME_STATS() 

TRUNCATE  TABLE NHL_DB.PUBLISHED.FACT_ALL_GAME_STATS;
INSERT INTO NHL_DB.PUBLISHED.FACT_ALL_GAME_STATS

WITH CTE_SOURCE_DATA AS (
SELECT GAMEID,GAMEDATE,
PLAYERTEAM AS HOME_TEAM,
OPPOSINGTEAM AS AWAY_TEAM,
GOALSFOR AS HOME_TEAM_SCORE,
GOALSAGAINST AS AWAY_TEAM_SCORE,
XGOALSFOR AS HOME_TEAM_XSCORE,
XGOALSAGAINST AS AWAY_TEAM_XSCORE,
ICETIME
FROM NHL_DB.RAW.ALL_TEAMS 
WHERE  SITUATION ='all'
AND HOME_OR_AWAY = 'HOME'
AND GAMEID NOT IN (SELECT DISTINCT GAMEID FROM NHL_DB.RAW.ALL_TEAMS
WHERE GOALSFOR=GOALSAGAINST AND ICETIME>3600 AND XGOALSFOR=XGOALSAGAINST)
)

SELECT 
GAMEID,GAMEDATE,HOME_TEAM,
T1.TEAM_ID AS HOME_TEAM_INDEX,
AWAY_TEAM,
T2.TEAM_ID AS AWAY_TEAM_INDEX,
CASE WHEN HOME_TEAM_SCORE=AWAY_TEAM_SCORE THEN HOME_TEAM_XSCORE ELSE HOME_TEAM_SCORE END AS HOME_TEAM_SCORE,
CASE WHEN HOME_TEAM_SCORE=AWAY_TEAM_SCORE THEN AWAY_TEAM_XSCORE ELSE AWAY_TEAM_SCORE END AS AWAY_TEAM_SCORE,
CASE WHEN (ICETIME-3600)>0 THEN 1 ELSE 0 END AS OVERTIME_FLAG
FROM CTE_SOURCE_DATA AS S
INNER JOIN NHL_DB.RAW.DIM_TEAMS AS T1
ON S.HOME_TEAM=T1.TEAM_NAME
INNER JOIN NHL_DB.RAW.DIM_TEAMS AS T2
ON S.AWAY_TEAM=T2.TEAM_NAME




